### ISSUE TITLE
Create a logo for Ocean

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/ocean#1]
## Summary

Create a logo for Sociomantic main core library we just open-sourced called Ocean.
## Brief Description

This is base library for D focused on high-performance applications. It's used to create applications that are fast and use networks mainly.
## Why Ocean is cool / important?

Ocean allows developers to create fast and efficient applications. Is the core library powering the whole Sociomantic high-performance backend.
## Ideas for the Logo

Obviously something oceany would be a must, but it would be nice to somehow convey also the feeling of speed, of something fast (but also vast, because the library includes a lot of different kind of utilities). Also something related to building blocks could be a possibility.

Sociomantic colours seem to be a good fit for something watery, but on the other hand there is also D involved, so red could be an option too.

Here is a similar library as an example: http://www.boost.org/
## Final Output

To be used on GitHub repo, stickers, etc. potentially even external website (if one is made).
## Extra Goodies

Colour scheme and suggested font for further work on a potential website.

**Comment by joseph-wakeling-sociomantic** [comment]
https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa ;-)

**Comment by gautam-kotian-sociomantic** [comment]
@alaksiej-stankievicx-sociomantic had an interesting idea in our internal chat about a ship on an ocean with "D" being its sail...

**Comment by dylan-cromwell-sociomantic** [comment]
I think there is a typo above @leandro-lucarella-sociomantic when it says "Why is Makd cool / important" shouldn't it be Ocean?

**Comment by leandro-lucarella-sociomantic** [comment]
> I think there is a typo above @leandro-lucarella-sociomantic when it says "Why is Makd cool / important" shouldn't it be Ocean?

Yes, of course, copy&paste error :)

**Comment by dylan-cromwell-sociomantic** [comment]
@leandro-lucarella-sociomantic this has been submitted to Design. I will follow the project to it's completion and post iterations here for your (and others') feedback. I have altered the deadline to 1 month later, 15/9/16 as I think giving 1 month is reasonable.

**Comment by mathias-baumann-sociomantic** [comment]
That schedule worked out great :>

**Comment by dylan-cromwell-sociomantic** [comment]
@leandro-lucarella-sociomantic as can be expected Design is very busy with their daily work and we are not at a presentable design. I've set a meeting to catch-up and see if we can help expedite the process at all. They've requested it be July or August. I will keep you updated with any significant news but as I've been doing I will not just post comments if there is nothing important to report.

**Comment by leandro-lucarella-sociomantic** [comment]
Same as with ocean, no worries! I'll remove the deadline here too as there is no real need for one.
