### ISSUE TITLE
Types unsupported by ocean.text.convert.Formatter can cause mysterious compilation errors in unittest builds

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#106]
e.g.:
```D
union MyUnion
{
    int i;
    float f;
}

import ocean.core.Array : removeShift;

void func ( )
{
    MyUnion[] arr;
    removeShift(arr, 0);
}
```
produces this error:
```
./submodules/ocean/src/ocean/text/convert/Formatter.d(489): Error: static assert  "Type unsupported by ocean.text.convert.Formatter: MyUnion"
./submodules/ocean/src/ocean/text/convert/Formatter.d(475):        instantiated from here: handle!(MyUnion)
./submodules/ocean/src/ocean/text/convert/Formatter.d(203):        instantiated from here: handle!(MyUnion[])
./submodules/ocean/src/ocean/text/convert/Formatter.d(69):        instantiated from here: sformat!(MyUnion[],char[],MyUnion[])
./submodules/ocean/src/ocean/core/Enforce.d(427):        instantiated from here: format!(MyUnion[],char[],MyUnion[])
./submodules/ocean/src/ocean/core/Enforce.d(334):        instantiated from here: enforceImpl!("==",MyUnion[],MyUnion[])
./submodules/ocean/src/ocean/core/Test.d(80):        instantiated from here: enforceImpl!("==",TestException,MyUnion[],MyUnion[])
./submodules/ocean/src/ocean/core/Buffer.d(123):        instantiated from here: test!("==",MyUnion[],MyUnion[])
./submodules/ocean/src/ocean/core/array/Mutation.d(1174):        instantiated from here: Buffer!(MyUnion)
./src/myrepo/MyModule.d(1138):        instantiated from here: removeShift!(MyUnion)
make: *** [/home/devel/myrepo/build/devel/tmp/allunittests] Error 1
```
It's not immediately obvious to the user why calling `removeShift` causes unittests to fail.

**Comment by nemanja-boric-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/core/Buffer.d#L123

I suggest simply replacing these tests with `enforce` (so the message is not rendered).

**Comment by gavin-norman-sociomantic** [comment]
Seems like a hack.

**Comment by mihails-strasuns-sociomantic** [comment]
I think I'd simply move buffer tests out of the template, it has already served its initial purpose.

**Comment by nemanja-boric-sociomantic** [comment]
> Seems like a hack.

I find all core components should be as self-contained as they can (in other words - they should be perfectly fine using only primitives from the language, and not all the convenience of the standard library). Making `Array` depends on `Formatter` is not worth it - you would expect from `Array` that it would work in all scenarios (I see these unittests more as a sanity check), so the potential error message has a little value, and for that it depends on such a way that restrictions of `Formatter` applies to `Array` (and this restriction can be perfectly valid - formatter has no way to render the non-discriminated union).

**Comment by gavin-norman-sociomantic** [comment]
>I think I'd simply move buffer tests out of the template, it has already served its initial purpose.

That seems fair.
