### ISSUE TITLE
PidLock extension should run before loggers

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#107]
In case logging system doesn't have enough permission to write to the log file, it can happen that
the application fails on permission denied exception, before trying to look for the other application instance.

While this  effectively prevents the application to run, it would be nice if the `PidLock` extension would check if the another instance is already running, before any other systems are started.

**Comment by gavin-norman-sociomantic** [comment]
I'm not sure this is about ordering. PID lock requires parsing the config file, doesn't it? Couldn't that also come up against permissions problems?

**Comment by nemanja-boric-sociomantic** [comment]
I forgot what happened to this one, I think it was the misconfiguration problem, not the real bug, but I forgot the details. Perhaps @joseph-wakeling-sociomantic can recall?
