### ISSUE TITLE
Make ocean.text.Search non-templated

### ISSUE THREAD

**Issue by gautam-kotian-sociomantic** [sociomantic-tsunami/ocean#130]
@don-clugston-sociomantic commented on an internal sociomantic project:

>The functions in ocean.text.Search are templated on the character type `T`. The constructor (actually `opCall`) takes this type from the parameter of the string passes to it. If it's a string literal it will be `immutable char` and if a variable it will be `char`. This is never what you want. Probably this could fixed by throwing `Unqual` everywhere in that module, but I don't think there's much point.

>Those Fructs were originally created to work around bugs in D's template instantiation, which forced you to explicitly specify the types. The bugs were fixed about a decade ago. Now the Fructs do the opposite, they create type mismatch problems! And that's the only thing they do. They don't do anything useful.

It is probably best to deprecate and later remove this module to prevent someone from trying to use it.

cc @mathias-lang-sociomantic

**Comment by nemanja-boric-sociomantic** [comment]
What would be the replacement for this? I agree, this Fructy thing isn't ideal, and I had to get away with explicit instantiation (which I made possible via https://github.com/sociomantic-tsunami/ocean/commit/cbe087208713f9b4bc54df52732f312a6fcf3a7f just because this reason):
 
```
    SearchFruct!(Const!(char))
```

But I don't think we have the replacement for the entire _module_.

**Comment by gavin-norman-sociomantic** [comment]
I'd missed this issue. We have at least two projects which make heavy use of ocean.text.Search, so it can't be deprecated.

**Comment by mihails-strasuns-sociomantic** [comment]
My understanding of @don-clugston-sociomantic proposal was that it would be good to remove `T` part of all these functions, making it all work on `const(char)[]` exclusively. That should keep exiting apps working, right?

Deprecating whole module is not an option of course.

**Comment by gavin-norman-sociomantic** [comment]
I see. I'll rename the issue, in that case.

**Comment by mathias-lang-sociomantic** [comment]
Looks like we missed that train in v4.x.x (other classes saw their support for different character type being removed).
Part of https://github.com/sociomantic-tsunami/ocean/issues/279 AFAIU.

**Comment by mihails-strasuns** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/687
