### ISSUE TITLE
Fix docker cache for travis builds

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/ocean#15]
Right now for some reason travis seems to be failing to cache the images that we pull and push to the docker registry to work as a cache, thus making the whole pulling and pushing just another time drain.

I already contacted Travis CI and they gave me some sort of experimental SSH access to the VM a job was run on, so I will be able to debug this and hopefully find a solution.

Since to be able to test this I need also for the docker pull/push is in a branch (PRs are not trusted with docker credentials), for now we should not disable the pull/push until I can have some time to investigate this. FYI @mihails-strasuns-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
Acknowledged

**Comment by nemanja-boric-sociomantic** [comment]
What's the status with this @leandro-lucarella-sociomantic ?

**Comment by leandro-lucarella-sociomantic** [comment]
WONT CLOSE

We tried several approaches to try to use a cache and everything was slower (or the same) as build from scratch.
