### ISSUE TITLE
Base64 should reject badly terminated data

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#196]
In case explicit padding, base64 decoder will throw an exception when there are more than two padding bytes. It should do the same when implicit padding is in use. Currently, old behavior is that it silently discards the last byte.

See #193

**Comment by mihails-strasuns-sociomantic** [comment]
Moving to v5 because:
- issue is low prio
- @nemanja-boric-sociomantic is on vacation and I am not 100% confident about required changes

**Comment by mihails-strasuns** [comment]
Closing as @nemanja-boric-sociomantic is not available anymore and I can't figure out what exactly was needed 😊
