### ISSUE TITLE
Deprecate ocean.text.convert.{Format,Layout,Layout_tango}

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#206]
Those modules have been replaced by `ocean.text.convert.Formatter` and should be deprecated as they don't play well with D2.
`Format` depends on `Layout_tango`, as does `Layout`.

Once https://github.com/sociomantic-tsunami/ocean/pull/203 and https://github.com/sociomantic-tsunami/ocean/pull/187 have been pulled, we will be able to deprecate `Layout_tango`. As 203 includes a breaking change, this will only happen in v4.0.0 at best.

Feel free to assign me.

**Comment by mathias-lang-sociomantic** [comment]
Along with those modules, we should also kill `ocean.core.RuntimeTraits`

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic this is now fully resolved in v4.x.x , correct?

**Comment by mathias-lang-sociomantic** [comment]
It is!
