### ISSUE TITLE
Convert all assertions to `verify`

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#212]
As discussed many time in the past, the different behaviour of assertions in D1/D2 is problematic. To quote some previous discussion:

>The main problem with the proposed "design by contract" model is the assumption that once the program is sufficiently tested in debug mode it is safe to remove assertions and contracts without compromising correctness (for better performance).

>However, in the case of a server application working primarily with external data, it is very hard to get to the point of such confidence, especially if any error can have a potentially very costly impact on business. Even full test coverage can be misleading. This has resulted in some application never using the -release flag out of fear of possible uncaught programmer errors.

>After some discussion, it was agreed that we need a more practical approach to using contracts, even if it will violate the intended DbC ideology. Most known issues seem to be associated with in contracts, because those do not notify the programmer when violation of some internal assumption occurs but rather at some later point when the violation is about to cause application corruption and must be protected against at all costs.

>At the same time, the actual performance penalty of calling such safety checks is often very small, being as simple as checking for null pointers or integer boundaries. Any possible performance gain is simply not worth the added risk of removing the check (one case where it can make a difference, though, is in very small functions where extra operations can make the difference between inlining or not).

Indeed, we are now at the stage of running important server apps in D2 builds and need to address this issue (the change of assertion behaviour) before progressing.

**Comment by leandro-lucarella-sociomantic** [comment]
Related to #213, I wonder if we should finally introduce this programming error before doing this conversion.

**Comment by mathias-lang-sociomantic** [comment]
How do we deal with bounds checking ?

**Comment by nemanja-boric-sociomantic** [comment]
It was discussed to move with the ocean compiled as a library with `-release`.

**Comment by mathias-lang-sociomantic** [comment]
It means we have to compile the whole project with `-release` or am I missing something ?

**Comment by mihails-strasuns-sociomantic** [comment]
> How do we deal with bounds checking ?

I don't see way out of it other than protect all places where it may happen with preceding `enforce`/`verify` of some sort.

> It  means we have to compile the whole project with -release or am I missing something ?

I think it should be the goal eventually but of course that requires similar adjustments of other libs and thus will take plenty of time. Idea of providing copy-paste makd snippet to link ocean as `-release` built static library is one way to make such slow transition less painful.

**Comment by leandro-lucarella-sociomantic** [comment]
> I don't see way out of it other than protect all places where it may happen with preceding enforce/verify of some sort.

This really sucks and I think is not practical. OK, we can minimize then the `Error` problem, but we can't rely on getting rid of it completely, which will still be somehow problematic.

**Comment by mihails-strasuns-sociomantic** [comment]
I actually don't think it is that bad. We rarely try to index arrays with some data that is not directly derived from its `.length` without previously doing some sanity checking on it - and that sounds like a reasonable approach overall. Code like this one https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/util/serialize/contiguous/Deserializer.d#L314 seems common.

**Comment by leandro-lucarella-sociomantic** [comment]
But the whole point of this is for times when someone forgets to do the sanity checks :)
I see your point about not being the end of the world though, but I think it is still risky to have cases where the program can explode in your face when it is avoidable.

**Comment by mihails-strasuns-sociomantic** [comment]
I agree with that but to me it seems much more likely to be caught at (unit)testing stage than failed contract and thus much further in the realm of acceptable.

**Comment by gavin-norman-sociomantic** [comment]
PR updating the error handling guidelines: https://github.com/sociomantic-tsunami/sociomantic/pull/10

**Comment by mihails-strasuns-sociomantic** [comment]
Also related - https://github.com/sociomantic-tsunami/ocean/issues/96

**Comment by gavin-norman-sociomantic** [comment]
Breakdown of `assert` occurrences by top-level package:
* `core`: 472
* `io`: 586
* `math`: 900
* `meta`: 191
* `net`: 202
* `stdc`: 14
* `sys`: 54
* `task`: 32
* `text`: 1339
* `time`: 601
* `util`: 1187

It might be a good idea to strip out unused code before doing this. (Or deprecate and not bother assessing deprecated code for assertions.)

**Comment by gavin-norman-sociomantic** [comment]
Some easy cases exist in old unittests that were never converted to use `test` instead of `assert`.

**Comment by gavin-norman-sociomantic** [comment]
>Some easy cases exist in old unittests that were never converted to use test instead of assert.

It might be possible to auto-convert these using d1to2fix. @mihails-strasuns-sociomantic what do you think?

**Comment by mihails-strasuns-sociomantic** [comment]
Shouldn't be too hard. I'll have a look.

**Comment by gavin-norman-sociomantic** [comment]
Excellent. Let's try to do that first, then we can assess what remains.

**Comment by gavin-norman-sociomantic** [comment]
After merging #241:
* `core`: 168
* `io`: 340
* `math`: 322
* `meta`: 29 (already done)
* `net`: 67
* `stdc`: 2
* `sys`: 37
* `task`: 38 (already done)
* `text`: 312
* `time`: 29
* `util`: 562

**Comment by gavin-norman-sociomantic** [comment]
(Adjusted numbers above, filtering out `static assert`.)

**Comment by gavin-norman-sociomantic** [comment]
Looks like splitting it six ways might work:
* io
* math
* text
* util part 1
* util part 2
* The rest

**Comment by mihails-strasuns-sociomantic** [comment]
I'd like to take `core` :)

**Comment by gavin-norman-sociomantic** [comment]
`core` is included in "the rest" ;)

**Comment by mathias-lang-sociomantic** [comment]
I volunteer as a tribute for text :)

**Comment by gavin-norman-sociomantic** [comment]
Thanks!

So we have:
* @mathias-lang-sociomantic `text`. #276
* Me `util.container`. #253
* @david-eckardt-sociomantic `math` #259 
* @mihails-strasuns-sociomantic `core`, `net`, `sys`, `time`. #255, #270, #265 (`time` doesn't contain anything worth changing)
* @nemanja-boric-sociomantic `io`. #251
* @nemanja-boric-sociomantic `util` excluding `util.container`. #264

**Comment by gavin-norman-sociomantic** [comment]
The easiest way to split `util` would be `util.container` and everything else. `container` has 387 / 562 asserts.

I'm happy to take `container`.

**Comment by mihails-strasuns-sociomantic** [comment]
This finished for initial conversion, right?

**Comment by mathias-lang-sociomantic** [comment]
I haven't done my share yet :blush:

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-lang-sociomantic do you think you can get to it in next few days? Otherwise I am going to take it over as I want to release 3.5.0 this Friday :)

**Comment by mathias-lang-sociomantic** [comment]
I definitely won't be able to start before Thursday *at best* (Brighton), so maybe it's better if you take over, sorry :(

**Comment by mihails-strasuns-sociomantic** [comment]
No problem!

**Comment by mihails-strasuns-sociomantic** [comment]
`ocean.text` merged - https://github.com/sociomantic-tsunami/ocean/pull/276

That should be it for the first stage.
