### ISSUE TITLE
Create a specialized `enforce` to check for programming errors

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/ocean#213]
We have an internal guide that recommends using `enforce` even for programming errors when checks are cheap, so we can compile applications with `-release` without risking very nasty stuff happening in the live system because of the lack of simple sanity checks.

The problem with this is then it is very difficult to tell which checks are checking for programming errors and which are checking for normal error conditions. On top of that, usually the former should not be caught and should make the application crash (maybe except for some critical applications) and the later should be normally caught and handled on a higher level of the application.

Because of this I think we should introduce a `ProgrammingError` `Exception` (or `Error` in D2), or maybe even use `AssertError`, but it might be nice to be able to tell how that error was raised), and an enforce function (with a different name... `ensure()`, `assure()`, `verify()`, `guarantee()`, `impose()`, `force()`?) that uses that error by default instead of `Exception`.

**Comment by leandro-lucarella-sociomantic** [comment]
This comes from an old internal issue that had a lot of discussion already, please feel free to post summaries of your POVs.

**Comment by gavin-norman-sociomantic** [comment]
>Because of this I think we should introduce a ProgrammingError Exception (or Error in D2)

It's important that this is _not_ an `Error` in D2! See #212.

**Comment by gavin-norman-sociomantic** [comment]
Of the possible names listed above, I would favour `verify`.

**Comment by gavin-norman-sociomantic** [comment]
By the way, this idea fits nicely with discussion around importing the existing `ocean.core.Enforce` module all over the place leading to cyclic imports. It was suggested that a minimal (i.e. with no dependencies) error-checking module be made for this use case.

**Comment by mathias-lang-sociomantic** [comment]
> It's important that this is not an Error in D2! See #212.

It's also important to note that this will make `nothrow` totally unusable for us in the future.

**Comment by gavin-norman-sociomantic** [comment]
Do `Error`s not "count" for the purposes of `nothrow` then?

(I do recall @mihails-strasuns-sociomantic making some very strong statements about `nothrow` and its evilness, in the past, anyway.)

**Comment by nemanja-boric-sociomantic** [comment]
Yes, they are not counted. I see `Error`s just like `abort` on steroids, really.

The issue @mihails-strasuns-sociomantic was mentioning IIRC is that from the `nothrow` method one needs to ensure that either there's an exception handler and all exceptions are caught or that _all_ methods being called are also `nothrow`.

**Comment by gavin-norman-sociomantic** [comment]
It sounds to me like `Error` was invented for the sake of `nothrow`, then.

**Comment by nemanja-boric-sociomantic** [comment]
You're not the first one who thinks that: http://forum.dlang.org/post/mailman.1047.1337882017.24740.digitalmars-d@puremagic.com

**Comment by gavin-norman-sociomantic** [comment]
Well, anyway, I think losing `nothrow` is a very small price to pay in order that vital servers don't crash due to unexpected bugs (what bugs are expected? haha).

**Comment by leandro-lucarella-sociomantic** [comment]
> Yes, they are not counted. I see Errors just like abort on steroids, really.

I wonder where the steroids are though :thinking:

**Comment by nemanja-boric-sociomantic** [comment]
Well, so that you can have some kind of the logging/last resort handler before you go and die. Something like multi platform `SIGABRT` handler (+ it wouldn't be a signal handler).

**Comment by leandro-lucarella-sociomantic** [comment]
Or something like [atexit()](https://linux.die.net/man/3/atexit)? :)

**Comment by leandro-lucarella-sociomantic** [comment]
Ah, maybe not, that only works on normal termination, I always thought it was always executed. But yeah, is nothing that you can't do with a little effort and IMHO is not something that is that useful generally (I wonder really how many people use such a feature) to make a completely parallel exception hierarchy of exceptions that don't really behave like exceptions, but sort of are...

**Comment by mihails-strasuns-sociomantic** [comment]
Interesting comparison - in Rust entity akin to `Error` (`panic`) is the only allowed from of exceptions at all. All regular error handling must be done with return codes exclusively. But by spec panic there is only obliged to terminate current thread, not the whole process.

**Comment by leandro-lucarella-sociomantic** [comment]
Go also followed the path of no exceptions + return codes + last resort handling for (almost) unrecoverable errors.

**Comment by nemanja-boric-sociomantic** [comment]
C as well :trollface:

**Comment by gavin-norman-sociomantic** [comment]
>Interesting comparison - in Rust entity akin to Error (panic) is the only allowed from of exceptions at all. All regular error handling must be done with return codes exclusively. But by spec panic there is only obliged to terminate current thread, not the whole process.

Sigh. This sounds great.
