### ISSUE TITLE
CpuMemoryStats: Add ability to specify the PID to get the stats for

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic-tsunami/ocean#309]
We have a use-case for this (and we already used custom parsing of `/proc/self/status` before `CpuMemoryStats` existed). In our test-suite, we can verify that the total memory usage of an application doesn't exceed some specified number. In our code it looks like this:

```D
public override void run ( )
{
    auto pid = (cast(TestedDaemonApplication)this.context.app).pid();

    Format.format(this.pid_buffer,
        "/proc/{}/status", pid);

    uint kbytes;

    Test(getVMSize(kbytes, this.pid_buffer));

    .log.info("Total memory used: {} MB", kbytes / 1024);

    // ensure less than 750 MB total used memory
    Test!("<=")(kbytes, 750 * 1024);
}
```

It would be handy if `CpuMemoryStats` had the ability to specify the PID (perhaps in the constructor), so we can get rid of our custom implementation and start using `CpuMemoryStats` instead.

**Comment by mihails-strasuns-sociomantic** [comment]
There is https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/sys/stats/linux/ProcVFS.d#L167 - and next turtle release will even include framework for tracking it (https://github.com/sociomantic/turtle/pull/304). You may want to comment on that PR btw if you already have something similar in your test suite.

**Comment by mihails-strasuns-sociomantic** [comment]
(and https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/sys/stats/linux/ProcVFS.d#L167 of course)

**Comment by andrej-mitrovic-sociomantic** [comment]
Oh sweet! In my case I'm testing for the exact memory usage after one run, rather than testing if memory increased at all between several runs.

**Comment by mihails-strasuns-sociomantic** [comment]
> Oh sweet! In my case I'm testing for the exact memory usage after one run

Yeah with that PR you will still be able to access it manually, something in the spirit of `(cast(TestedDaemonApplication) this.context.app).getPeakStats()` in the very last test. Should be easier than reimplement same tracking from scratch.
