### ISSUE TITLE
Should IPSocket.socket call ISocket.socket?

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#323]
`ISocket.socket`: https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/sys/socket/model/ISocket.d#L309-L318
`IPSocket:socket`: https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/sys/socket/IPSocket.d#L228-L238

Looks like a refactoring error that they are both separate implementations.

@david-eckardt-sociomantic what do you think?

**Comment by david-eckardt-sociomantic** [comment]
I agree. `IPSocket.socket` should call
```d
super.socket(this.is_ipv6? AF_INET6 : AF_INET, type, protocol)
```
