### ISSUE TITLE
Add v3.6.0 to LibFeatures

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#338]

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/LibFeatures.d#L20 ??

**Comment by nemanja-boric-sociomantic** [comment]
Ah good if already added. This was just a reminder not to forget it.
