### ISSUE TITLE
Possible problem with URI URL encoder

### ISSUE THREAD

**Issue by ben-palmer-sociomantic** [sociomantic-tsunami/ocean#354]
The URL encoder in the `ocean.net.Uri` module seems to be encoding non-reserved characters in `IncScheme` mode which is not recommended in the specification (https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/net/Uri.d#L189).

For example `_` is not a reserved character but is encoded. I may have misunderstood what the `IncScheme` mode is supposed to do but to my mind it should follow the specification. See https://tools.ietf.org/html/rfc3986#section-2.2 for the reserved character list.

Note that the `EncodeNonUnreserved` class in `ocean.net.util.UrlEncoder` does the encoding correctly.

**Comment by mihails-strasuns-sociomantic** [comment]
> I may have misunderstood what the IncScheme mode is supposed to do

It should be responsible for scheme part of the URI:

```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
```

The spec you have linked defined (https://tools.ietf.org/html/rfc3986#section-3.1) scheme grammar like this:

```
scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )
```

So it seems correct that these symbols are escaped for scheme.

**Comment by mihails-strasuns-sociomantic** [comment]
(unless there is more specific issue to check, I'd close this as `res-invalid`)

**Comment by ben-palmer-sociomantic** [comment]
> (unless there is more specific issue to check, I'd close this as res-invalid)

My issue was that there is inconsistency between the `UrlEncoder` and `Uri` classes as far as encoding goes and this can be the source of bugs. AFAICS there is no way to encode a URL correctly using the `Uri` class.

**Comment by mihails-strasuns-sociomantic** [comment]
I may be misunderstanding but it looks like `Uri` expects one to parse URI in blocks first and encode each with a particular matching scheme.

In other words, specified characters are correct - the problem comes from trying to encode whole URI with a single scheme. Using `produce` (https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/net/Uri.d#L450) which automatically picks schemes for a parsed chunks should provide result matching RFC.

**Comment by mihails-strasuns-sociomantic** [comment]
(maybe `encode` was not supposed to be public?)

**Comment by ben-palmer-sociomantic** [comment]
> In other words, specified characters are correct - the problem comes from trying to encode whole URI with a single scheme. Using produce (https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/net/Uri.d#L450) which automatically picks schemes for a parsed chunks should provide result matching RFC.

Ok, that wasn't obvious to me when I first looked at this. Might be good to have an example unit test for it as well as the current one just uses `encode`.

**Comment by mihails-strasuns-sociomantic** [comment]
Sounds like a good idea.
