### ISSUE TITLE
Rename CpuMemoryStats.log to something else

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#363]
The `CpuMemoryStats.log` method is a bit of deceptive, since this method actually calculates the CPU usage in the previous time interval, records the memory usage and returns the filled struct to the user which then _logs_ it via different means (usually, it's the statslog.)

https://github.com/sociomantic-tsunami/ocean/blob/f74ae1a5730a683065481def021708c7dd6babd8/src/ocean/sys/Stats.d#L151

**Comment by gavin-norman-sociomantic** [comment]
`collect` would be one alternative.
