### ISSUE TITLE
Compiling with -profile fails

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#365]
```
Error: cannot mix core.std.stdlib.alloca() and exception handling in _D5ocean4util6digest6Digest6Digest9hexDigestMFAaZAa()
```
`alloca`: https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/digest/Digest.d#L138
Exception handling: https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/digest/Digest.d#L141

**Comment by nemanja-boric-sociomantic** [comment]
I'm looking into that method, and I can't find a compelling reason why that `verify` is needed.

**Comment by mihails-strasuns** [comment]
Fixed in https://github.com/sociomantic-tsunami/ocean/commit/71f437844f79e44cd2fa04ae3ef0a2826e22623e
