### ISSUE TITLE
`toDString` should accept `Const!(char)*`

### ISSUE THREAD

**Issue by jens-mueller-sociomantic** [sociomantic-tsunami/ocean#40]
The function `toDString` in `ocean.text.util.String` should be more general by accepting `Const!(char)*` instead of `char*`. Consider the case when you have a C string

```d
Const!(char)* c_string = "test";
auto d_string = StringC.toDString(c_string); // does not compile with D2
```

Currently you cannot call `toDString` because `c_string` is `const`. You can easily end up with a `const` C string when calling a C library. As a work around you can copy `c_string` to a `char*`. To me the proper fix is allow passing `Const!(char)*` since `toDString` [does not modify the memory pointed to by its argument](https://github.com/sociomantic-tsunami/ocean/blob/v2.x.x/src/ocean/text/util/StringC.d#L136). Also it is nice to indicate (via its signature) to the caller that it does not perform such modifications. Since the change accepts more input existing code is unaffected by the change.

Same reasoning holds for `toDString` accepting currently a  `Wchar*`.

**Comment by mathias-lang-sociomantic** [comment]
Actually it should accept `inout` since it's the textbook reason for its existence.

**Comment by jens-mueller-sociomantic** [comment]
True. If `inout` works out that would be even better.
