### ISSUE TITLE
3.6.0 release uses deprecated functionality internally

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/ocean#402]
It looks like some deprecated ocean functionality is still being used in other parts of ocean.  From a recent app build:

```
./submodules/ocean/src/ocean/util/app/ext/VersionArgsExt.d(269): Deprecation: alias ocean.io.stream.Format.FormatOutput!(char).FormatOutput.opCall is deprecated - Use the 'format' method instead, or 'flush'
./submodules/ocean/src/ocean/util/app/ext/VersionArgsExt.d(269): Deprecation: function ocean.io.stream.Format.FormatOutput!(char).FormatOutput.print is deprecated - Use the 'format' method instead, or 'flush'
```

This also suggests that ocean unittests may be failing to cover some parts of the app framework and its extensions.

**Comment by mihails-strasuns-sociomantic** [comment]
> This also suggests that ocean unittests may be failing to cover some parts of the app framework and its extensions.

I checked the code and it is one piece that was explicitly disabled for unit tests to avoid spamming to console :)

**Comment by joseph-wakeling-sociomantic** [comment]
> I checked the code and it is one piece that was explicitly disabled for unit tests to avoid spamming to console :)

Well, I guess that worked in its own terms ... :-)

**Comment by joseph-wakeling-sociomantic** [comment]
Just for reference: there appears to be one other place where deprecated functionality is exposed, this time only in unittests (not in production):

```
rdmd build/devel/tmp/allunittests
Deprecation: Please change toString to accept `scope FormatterSink` instead of `size_t delegate(cstring)` in Foo
```

This looks like it comes down to this: https://github.com/sociomantic-tsunami/ocean/blob/71e4cd854ca331484f194a278f9cb0296e48b343/src/ocean/text/convert/Formatter_test.d#L26-L33

... which would be straightforward enough to fix by wrapping the `Foo` test case in a `deprecated unittest` block, and leaving `Bar` in a regular `unittest` block.  But I don't know if there is a reason for wanting that deprecation reported during unittests.

**Comment by mathias-lang-sociomantic** [comment]
The "deprecation" comes from a `pragma(msg, ...)` so this one cannot be removed (and that's also why it doesn't fail the CI). This test is here on purpose.

**Comment by joseph-wakeling-sociomantic** [comment]
OK, no problem.  I'm in the mood for writing a simple fix or two so wanted to check if this was a desired (and feasible) one ;-)
