### ISSUE TITLE
v3.6.0 introduces symbol clashes between hasIndirections definitions

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/ocean#405]
Building an application where `ocean.core.Traits.hasIndirections` is used inside one module with v3.6.0 I now get a symbol clash with `ocean.meta.traits.Indirections.hasIndirections`:

```
Error: ocean.meta.traits.Indirections.hasIndirections(T...) at
./submodules/ocean/src/ocean/meta/traits/Indirections.d(51)
conflicts with ocean.core.Traits.hasIndirections(T...) at
./submodules/ocean/src/ocean/core/Traits.d(228)
```

My guess would be that the `ocean.meta.traits.Indirections` module is somehow accidentally publicly imported via some other module, in a way that wasn't previously the case.  This is arguably a breaking change (albeit an unintended one) so would be nice to fix if possible.

**Comment by joseph-wakeling-sociomantic** [comment]
It looks like it's down to commit 264378d68f4f8f8cd2535a0aa2b2e0e217260e33, which adjusts the traits import used in `ocean.task.Scheduler`.  Specifically, I would imagine the selective import of `hasIndirections` is causing it to be exposed publicly to any module that imports `ocean.task.Scheduler`.

**Comment by joseph-wakeling-sociomantic** [comment]
As a note: I only observe the problem in D2 builds.  Reverting commit 264378d68f4f8f8cd2535a0aa2b2e0e217260e33 means I no longer see the build error.

**Comment by mihails-strasuns-sociomantic** [comment]
Sorry, but I am inclined to close this as wont-fix. It is a known and in general unfixable problem that introducing new symbols can cause downstream breakage in D - we have made a conscious decision to ignore that in our neptune rules because otherwise every single addition of a symbol would require a major release. This is unfortunate but I don't see what can be done about in.

**Comment by joseph-wakeling-sociomantic** [comment]
Actually it looks like a fairly simple fix: https://github.com/sociomantic-tsunami/ocean/pull/407

**Comment by mihails-strasuns-sociomantic** [comment]
I know that this can be simply fixed - I argue that it should not be done on principle, because cases like that are not considered breaking changes. Where is the line between case that should be fixed and the one that should not?

**Comment by joseph-wakeling-sociomantic** [comment]
> Where is the line between case that should be fixed and the one that should not?

If the fix was complicated or problematic, then I would agree it might not be worth addressing it.  But the fix in this case is super-simple with no apparent negatives, so why not take it?

**Comment by mihails-strasuns-sociomantic** [comment]
The fix is always simple - renaming problematic symbol or getting rid of it. But it can only be known in retrospective, by checking if it clashes for code of our application and "fixing" that - it is not something one can do during initial development and not even something one can fix for arbitrary code out there.

Now in this specific case everything is indeed much more simple as one doesn't need to hide the symbol somehow as selective import was not strictly necessary in the first place. But from the downstream app PoV error you get is not different from clashing with some added method - and the point I am trying to make is that those kinds of errors are _in general_ supposed to be handled downstream.

**Comment by joseph-wakeling-sociomantic** [comment]
Maybe the point is that in this case the reason for the problem was due to use of something -- a selective import -- that is definitely known to be problematic.  The selective import arguably shouldn't have been used in the first place because of the risk of this sort of thing happening.

So with that in mind -- that it's code which is _obviously_ problematic on the library-writer's side -- I would argue that it's reasonable to expect this to be fixed.  Because it's not a problem that arises only contingent on the downstream user's use of the library: it's inherent in the way the library code was written.

**Comment by joseph-wakeling-sociomantic** [comment]
Anyway, thanks for taking it in.  Just for reference: I did consider completely rewriting things on the downstream app side to use `ocean.meta`, and the particular missing piece of functionality was an equivalent for `ocean.core.Traits.FieldType`.  Or did I miss something myself?

**Comment by mihails-strasuns-sociomantic** [comment]
Oh, great, maybe you will be the one who explains me why that utility was needed and in what cases `typeof(S.tupleof[i])` was not enough :) `ocean.meta` is filled with utils on-demand for now so it misses quite some stuff from old traits, but this one was going to be omitted intentionally as I couldn't find the problem it fixes.

**Comment by joseph-wakeling-sociomantic** [comment]
@mihails-strasuns-sociomantic fair point.  `FieldType` offers a simple and clearly-named template whose purpose is clear and whose implementation details don't need to be worried about.  I don't mind if you don't want to include it in `ocean.meta` but it doesn't seem unreasonable to want to be able to mix `fieldIdentifier` and `FieldType` side by side.

**Comment by joseph-wakeling-sociomantic** [comment]
For the record: the patch did not fix the problem generally, because plenty of other places use selective imports of `ocean.meta` functionality.

I'll leave it up to you whether it is worth addressing this issue (perhaps we might introduce a ban on selective imports at module level, and replace all these cases?).  For the specific problem case I'm encountering, I'm going to just replace all uses of `ocean.core.Traits` in the app, so that we're not blocked on either a decision or a fix about whether to address this `ocean`-side.

**Comment by joseph-wakeling-sociomantic** [comment]
The specific problem is recurring because the `IScheduler` module still uses a selective `hasIndirections` symbol import.  Searching for other examples, I found plenty of selective `ocean.meta` imports elsewhere in ocean.
