### ISSUE TITLE
Collectd integration test is outdated

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/ocean#420]
It was disabled because it requires external daemon setup but now it doesn't even compile with recent ocean. Will need to be updated.

**Comment by mihails-strasuns-sociomantic** [comment]
Original PR - https://github.com/sociomantic/ocean/pull/690 but looks like original introduced test already has some of present problems. @mathias-lang-sociomantic would you mind having a look? :)

**Comment by nemanja-boric-sociomantic** [comment]
Should/Could we actually compile as part of tests, but not run (or run trivially just returning out of the main)?

**Comment by mihails-strasuns-sociomantic** [comment]
I assumed there is some value in actually being able to run it with collectd being installed. So alternative would be to just move it to `examples/`

**Comment by mihails-strasuns-sociomantic** [comment]
Fixed via https://github.com/sociomantic-tsunami/ocean/pull/425
