### ISSUE TITLE
Error message is not displayed when command line options are missing or incomplete

### ISSUE THREAD

**Issue by tiyash-basu-sociomantic** [sociomantic-tsunami/ocean#429]
If a command line argument is set to be `required`, not mentioning it while running the executable does not show any error message. Also, not specifying the value of a command line option does not cause any error message to be displayed.

**Comment by nemanja-boric-sociomantic** [comment]
Hmm, I'm pretty sure I've seen these errors (notably, missing `--config` option). Care to attach the minimal reproducible case?

**Comment by tiyash-basu-sociomantic** [comment]
This is the commit where it seems to have been broken: 480fb9fcd71a89e8e93fe917937fda258b08a5aa

@mathias-lang-sociomantic

**Comment by tiyash-basu-sociomantic** [comment]
Here is a minimal reproducible case:

```D
module foo.main;


import ocean.meta.types.Qualifiers;
import ocean.util.app.CliApp;


/// Foo class
class Foo : CliApp
{

    /// Constructor
    public this ( )
    {
        istring name = "name";
        istring desc = "description";
        auto ver = VersionInfo.init;

        super(name, desc, ver);
    }

    override protected int run ( Arguments args )
    {
        return 0;
    }

    override protected void setupArgs ( IApplication app, Arguments args )
    {
        args("source")
            .aliased('S')
            .params(1)
            .required;
    }

    override protected istring validateArgs ( IApplication app, Arguments args )
    {
        return null;
    }
}


/// Main
int main ( istring[] args )
{
    return (new Foo).main(args);
}

```
Upon compiling and running this without `-S` option, no error is being displayed.

**Comment by nemanja-boric-sociomantic** [comment]
Thanks!

**Comment by mathias-lang-sociomantic** [comment]
Fix in https://github.com/sociomantic-tsunami/ocean/pull/431

**Comment by nemanja-boric-sociomantic** [comment]
#431 merged.
