### ISSUE TITLE
Document supported format string in Formatter

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#43]
It's a common request, and would be nice to have comprehensive docs on that.
The format is inherited from `Layout`, and is currently DMD-style documentated (read the code).

**Comment by joseph-wakeling-sociomantic** [comment]
Thanks @mathias-lang-sociomantic.  This will fill a VERY longstanding hole in the library documentation.

It's probably a good idea to also include this documentation in the old `Format` and `Layout` modules, even though those may be planned for long-term deprecation.
