### ISSUE TITLE
Rotating version.log files

### ISSUE THREAD

**Issue by gautam-kotian-sociomantic** [sociomantic-tsunami/ocean#437]
Quoting from https://github.com/sociomantic-tsunami/ocean/pull/434#issuecomment-357923520

>As for version.log it is configured here https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/ext/VersionArgsExt.d#L297-L309 and seems like it is working as intended - this file is only written to during app startup, thus there is nothing to rotate.

Normally, the logrotate configurations of apps are wildcard-based (i.e. `/path/to/app/directory/log/*.log`). This means that from logrotate's point-of-view, `version.log` is also a candidate for rotation.

`version.log` is indeed written to only during app startup, so under normal circumstances, it would fill up rather slowly. But if it ever gets rotated, then the app would never reopen this file - meaning that the app will keep writing the version to the now rotated `version.log.1` file.

This is why I feel that at least for the sake of completeness, `version.log` should also be registered with `ReopenableFilesExt`.

**Comment by gavin-norman-sociomantic** [comment]
>But if it ever gets rotated, then the app would never reopen this file - meaning that the app will keep writing the version to the now rotated version.log.1 file.

The app only writes one line to this file, ever, though. Once at startup. So it doesn't "keep" writing anything.

**Comment by nemanja-boric-sociomantic** [comment]
Yes, if there are not too many hoops to jump though, application should actually just close this file after writing into it.

**Comment by gavin-norman-sociomantic** [comment]
Or are you referring to the race condition where the app opens the file, the file is rotated, then the app writes its one line into the file?

**Comment by mihails-strasuns-sociomantic** [comment]
That should still work I think, it will simply result in line being written to the new file.

**Comment by gautam-kotian-sociomantic** [comment]
>The app only writes one line to this file, ever, though. Once at startup. So it doesn't "keep" writing anything.

Yep, agreed. This is why I said `under normal circumstances, it would fill up rather slowly`. But the logrotate configuration allows rotation to be carried out at any arbitrary file size. Which means, if a user sets the rotation to happen at a very small file size, then it is quite possible that this file gets rotated.

>Yes, if there are not too many hoops to jump though, application should actually just close this file after writing into it.

Even if the application closes the file, it is still subject to logrotate's rotation settings.

**Comment by gautam-kotian-sociomantic** [comment]
>Or are you referring to the race condition where the app opens the file, the file is rotated, then the app writes its one line into the file?

No, I'm not referring to such a race condition.

**Comment by mihails-strasuns-sociomantic** [comment]
> then it is quite possible that this file gets rotated.

Yes, and that is 100% OK! What wrong would you expect to happen after rotation? Next time you restart the app it will simply write to (new) `version.log` again.

**Comment by gautam-kotian-sociomantic** [comment]
>Next time you restart the app it will simply write to (new) version.log again.

Hmm, yeah you're right. I guess this is not really an issue. Sorry for the noise.

**Comment by mihails-strasuns-sociomantic** [comment]
Welcome :)

**Comment by nemanja-boric-sociomantic** [comment]
I'll reopen this ticket for the simple issue: consistency - the logrotate will, in the sane default configuration that rotates all files inside `log` directory, rotate all files and it will instruct the application to reopen the files, one by one. Passing the `version.log` to the command socket will lead to error since this file is not registered with it.

I think adding this file to the list of the reopenable files is a small price to pay for the uniformity and simplicity of the logrotate scripts.
