### ISSUE TITLE
Deprecate usage of task as `ISuspendable`

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/ocean#461]
Currently ocean implemeted `ISuspendable` interface for tasks and uses that in some examples with suspendable throttler. It is not correct though - throttler expects to be able resume and suspend from any context and with tasks it is only legal to suspend from within a task and resume externally.

**Comment by mihails-strasuns-sociomantic** [comment]
Sadly, one can't deprecate implementing an interface - thus this will have to wait for v5 to be directly removed.

**Comment by mihails-strasuns** [comment]
Moving to `4.4.0+breaking` because of how much of a negative impact this issue brings.
