### ISSUE TITLE
Remove catch of ArrayBoundsCheckException in QueryParams

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#471]
https://github.com/sociomantic-tsunami/ocean/blob/fb5f7928e46e3d75c2a251f0dc54c901e3392f9d/src/ocean/net/util/ParamSet.d#L152-L163

**Comment by david-eckardt-sociomantic** [comment]
Hm... why is this a bug? It is D2 incompatible, but I don't see what's broken.

**Comment by mathias-lang-sociomantic** [comment]
It can cause different behavior between D1 and D2. From a more philosophical PoV, it also instruct the reader that `ArrayBoundsException` are expected / part of the normal flow.

**Comment by mihails-strasuns-sociomantic** [comment]
Anything that causes semantical mismatch between D1 and D2 build behavior is considered a bug.

**Comment by mihails-strasuns-sociomantic** [comment]
We should probably deprecate all `*Exception` aliases that forward to `*Error` at this point. There is no legitimate case when using those is not a bug in stage 3/4.
