### ISSUE TITLE
Spurious failures in src/ocean/task/util/Timer_test.d on dlang/ci

### ISSUE THREAD

**Issue by wilzbach** [sociomantic-tsunami/ocean#472]
```
allunittests: ocean.task.util.Timer_test: testing ...Unhandled exception in epoll/scheduler
	unit test has failed (./src/ocean/task/util/Timer_test.d:124)
submodules/makd/Makd.mak:577: recipe for target '/var/lib/jenkins/dlang_projects@4/sociomantic-tsunami/ocean/build/production/tmp/allunittests.stamp' failed
make: *** [/var/lib/jenkins/dlang_projects@4/sociomantic-tsunami/ocean/build/production/tmp/allunittests.stamp] Aborted (core dumped)
```

https://ci.dlang.io/blue/organizations/jenkins/dlang-org%2Fphobos/detail/PR-6288/2/pipeline

If there's no obvious fix to this, we could also consider disabling the test. There's `DETERMINISTIC_HINT` set on the script and otherwise we often also simply remove the files of such spurious tests before the execution.

See also:
- https://github.com/dlang/ci/blob/master/vars/runPipeline.groovy
- https://github.com/sociomantic-tsunami/ocean/blob/v4.0.4/src/ocean/task/util/Timer_test.d

**Comment by mihails-strasuns-sociomantic** [comment]
@wilzbach as a very blind fix attempt, could you try switching https://github.com/dlang/ci/blob/master/vars/runPipeline.groovy#L200 to use one of later non-alpha releases, for example https://github.com/sociomantic-tsunami/ocean/releases/tag/v4.0.4 ?

**Comment by wilzbach** [comment]
I can even do one better and remove the hard-coding and always let the Project Tester use the latest, stable version: https://github.com/dlang/ci/pull/188

In case you are interested, the script is:

```
git ls-remote --tags https://github.com/sociomantic-tsunami/ocean | sed -n "s|.*refs/tags/\\(v\\?[0-9]*\\.[0-9]*\\.[0-9]*\$\\)|\\1|p" | sort --version-sort | tail -n1
```

The error only appeared a few times over the last few weeks, so it might be hard to reproduce, but will try to keep an eye on it.

(feel free to close this if you haven't heard back in the next six weeks)

**Comment by mihails-strasuns-sociomantic** [comment]
Thanks!
