### ISSUE TITLE
Provide a means to not use a reopen signal with ReopenableFilesExt

### ISSUE THREAD

**Issue by gautam-kotian-sociomantic** [sociomantic-tsunami/ocean#486]
Currently, `ReopenableFilesExt` always registers a signal to reopen log files (if the application doesn't pass anything explicitly, then `SIGHUP` is registered by default).

However, in my application I'm sending the command to reopen log files via a UNIX socket, and hence do not need any reopen signal.

I'm using this as a workaround for now:
```d
       // Use an invalid signal as the reopen_signal for ReopenableFilesExt
       // (since we use a UNIX socket to send the command to reopen log files).
       settings.reopen_signal = 0;
```

**Comment by gautam-kotian-sociomantic** [comment]
It seems like the code I have in the issue description above is not really a workaround, but an *official* way of preventing a reopen signal being registered. At least [this check](https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/DaemonApp.d#L432) suggests that is the case.

So if I set `settings.reopen_signal` to zero, no signal handler gets set up effectively disabling the reopen signal. If this was indeed the intention, it perhaps needs to be documented better (preferably [here](https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/DaemonApp.d#L295-L296)).

**Comment by gautam-kotian-sociomantic** [comment]
But I think there may still be a bug. I wasn't bitten by it because I don't explicitly create the `ReopenableFilesExt` extension. I simply rely on DaemonApp to create it, so it is [created without any arguments](https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/DaemonApp.d#L430) and consequently [this check](https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/ext/ReopenableFilesExt.d#L99) fails.

But if an application creates the `ReopenableFilesExt` instance and in doing so passes a `SignalExt` instance as the first parameter to the constructor, then `setupSignalHandler()` will definitely be called (even if `reopen_signal` was passed as zero).

**Comment by mihails-strasuns-sociomantic** [comment]
Fixed in https://github.com/sociomantic-tsunami/ocean/pull/488
