### ISSUE TITLE
enforce() takes an istring, but could take a cstring instead

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic-tsunami/ocean#507]
If you call enforce with `enforce(condition, "literal" ~ some_string)`, this will error in D2 because the concatenation creates a mutable string which can't be passed to `enforce` because it takes an `istring`.

Can we use `cstring` instead?

**Comment by nemanja-boric-sociomantic** [comment]
IIRC, the reason for taking `istring` is that the `Exception`'s constructor is taking an `istring`, so we would have to `idup` it in the `enforce` which is tricky to track.

**Comment by nemanja-boric-sociomantic** [comment]
https://github.com/dlang/druntime/blob/master/src/object.d#L1889

**Comment by andrej-mitrovic-sociomantic** [comment]
I see. It looks like that's exactly what `enforce` in Phobos does, it duplicates the string. Sad!

**Comment by nemanja-boric-sociomantic** [comment]
I'm going to close this as wont-fix, please let me know if you think it should be reopened.

**Comment by david-eckardt-sociomantic** [comment]
A solution could be to use a template for the type of `msg` and `idup` unless it is `immutable`:
```d
public void enforceImpl ( T, Msg : cstring ) ( lazy Exception e, T ok, lazy Msg msg,
    istring file, int line)
{
    if (!ok)
    {
        // ...
        static if (is(Msg == immutable))
            auto message = msg;
        else
            auto message = msg.idup;
        // ...
    }
}
```
`Msg` would propagate to `enforce`, too. (I'm not sure if there might be a conflict with the `msg = ""` default argument value).

**Comment by mihails-strasuns-sociomantic** [comment]
@david-eckardt-sociomantic I have intentionally reasoned against it to ensure all `.dup` calls happen in application code where it is easier to decide if such allocation is acceptable (and prevent hidden performance issues)

**Comment by david-eckardt-sociomantic** [comment]
Fair enough.
