### ISSUE TITLE
AppendFile uses the file instance to register itself, while other appenders use ClassInfo

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#511]
`AppendFile` is special in a way that the registering is done by the name, and not by the 
classinfo: https://github.com/sociomantic-tsunami/ocean/blob/d7e97a4c55a56cb0fc330a663754c7983deb4e7c/src/ocean/util/log/AppendFile.d#L53

Other appenders use `classinfo` to register themselves:

https://github.com/sociomantic-tsunami/ocean/blob/d7e97a4c55a56cb0fc330a663754c7983deb4e7c/src/ocean/util/log/Appender.d#L228

The latter does match the documentation, but I'm not sure what the consequences are:

https://github.com/sociomantic-tsunami/ocean/blob/d7e97a4c55a56cb0fc330a663754c7983deb4e7c/src/ocean/util/log/Appender.d#L111-L114

**Comment by mihails-strasuns** [comment]
As long as actual instances are unique, I don't think there is any problem here.

**Comment by nemanja-boric-sociomantic** [comment]
I wouldn't characterize this as a bug anymore. I tried diving into the logging system, but it's really hard to figure out will the proposed change have any further impact and knowing this framework, it most likely it has.
