### ISSUE TITLE
Log when a fiber exits with an exception?

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#513]
This is a common source of hard to track down bugs. A simple error log would be really helpful.

Thoughts?

**Comment by nemanja-boric-sociomantic** [comment]
The stack trace is already ruined in case of the `MessageFiber`, as we rethrow the exception that killed the fiber:

https://github.com/sociomantic-tsunami/ocean/blob/c3d2a59dbb09a1743249b33f3c7e55cdc0008977/src/ocean/core/MessageFiber.d#L669

I see no problem adding a log event at the `MessageFiber` level.

**Comment by david-eckardt-sociomantic** [comment]
It should be logged inside the fiber just before it terminates. At this point the stack trace should still be valid, it becomes invalid after the context switch when the fiber has terminated.

**Comment by david-eckardt-sociomantic** [comment]
... as you said :)
> I see no problem adding a log event at the MessageFiber level.

**Comment by mihails-strasuns** [comment]
For tasks it is already possible by setting custom `theScheduler.exception_handler`. And `MessageFiber`/`SelectFiber` are not planned to be supported further more than absolutely necessary, thus closing.
