### ISSUE TITLE
Implement getGroupName

### ISSUE THREAD

**Issue by andrej-mitrovic-sociomantic** [sociomantic-tsunami/ocean#518]
If say for example you had a convention where you stored all your temporary files to `/srv/organization/team-name/tmp` where each team has their own temporary directory, then it would be useful for an application to be able to get the group name so it can automatically write to the appropriate temporary directory.

For example:

```D
/*******************************************************************************

    Returns:
        the path to the temporary folder for the current user's group.

*******************************************************************************/

string getGroupTempPath ( )
{
    import std.exception;
    import std.file;
    import std.process;
    import std.range;
    import std.string;

    auto result = executeShell("groups");
    enforce(result.status == 0, "Error: " ~ result.output);

    auto group = result.output.strip.split(" ").front;
    auto temp_path = format("/srv/team/%s/tmp", group);
    enforce(temp_path.exists, format("Temporary path '%s' not found. " ~
        "Please provide one with the --temp-path argument",
        temp_path));

    return temp_path;
}
```

It would be nice to have a solution that works in D1, maybe through the use of `getlogin` and `getgrouplist`, although the latter function seems to be pointlessly complicated..

**Comment by nemanja-boric-sociomantic** [comment]
You could just combine http://man7.org/linux/man-pages/man2/getgid.2.html and https://linux.die.net/man/3/getgrgid

**Comment by nemanja-boric-sociomantic** [comment]
Or did I misunderstood. You want to get list of all the groups that user belongs to (I got distracted by the singular in the `getGroupName`)?

**Comment by nemanja-boric-sociomantic** [comment]
(there's also `getgroups` with the easier to use API).

**Comment by andrej-mitrovic-sociomantic** [comment]
Hi Nemanja Boric Sociomantic.

I just want my app to write to a temporary directory. But using `/tmp` is disallowed because of reasons.

Have a great day!

**Comment by nemanja-boric-sociomantic** [comment]
Hello Andrej Mitrovic Sociomantic.

So for this to work out, you need the list of all the groups that user is in and then you'll
try to "guess" the temporary directory? I just want to understand what this ticket is about - it's
about querying the list of the groups the user belongs to, right?

Yours truly,
Nemanja

**Comment by nemanja-boric-sociomantic** [comment]
Or is it just getting the name of the current effective group? (your example just uses the first group).

**Comment by andrej-mitrovic-sociomantic** [comment]
Resolved IRL.
