### ISSUE TITLE
UnixSocket: Let handlers interact with users

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#52]
Working on https://github.com/sociomantic-tsunami/ocean/issues/37 I found myself wishing a way to interact with the user. Currently commands are one-shot: One send a command, an action is performed and one or multiple messages are sent back.

However, certain actions are complex or dangerous, in which case the handler might want to interact with the user. For example, here's an example of using `adduser`:

```
% sudo adduser test
Adding user `test' ...
Adding new group `test' (1002) ...
Adding new user `test' (1001) with group `test' ...
The home directory `/home/test' already exists.  Not copying from `/etc/skel'.
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully
Changing the user information for test
Enter the new value, or press ENTER for the default
	Full Name []: Test
	Room Number []: 42   
	Work Phone []: 
	Home Phone []: 
	Other []: 
Is the information correct? [Y/n] Y
```

In the case of reconfiguring loggers it's even more sensible, because one might just want to change the logger level. However, the config currently allow to:
- Change the level
- Toggle write to console
- Change the file the logger is writing to
- Change the console layout
- Change the file layout
- Propagate settings

While it is possible to handle this via a variety of method, a mean to interact with the user would be welcome. However, AFAICS it would require some redesign of `UnixSocketHandler`.

**Comment by nemanja-boric-sociomantic** [comment]
> However, AFAICS it would require some redesign of UnixSocketHandler.

Correct, and this is something that we want to do anyway, but it shouldn't be a problem, given ocean existing infrastructure.

**Comment by nemanja-boric-sociomantic** [comment]
I will look into this.

**Comment by nemanja-boric-sociomantic** [comment]
This is fixed in v4.x.x. Closing.
