### ISSUE TITLE
Decouple boiler-plate in UnixSocketExt away from the application extension

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#523]
`UnixSocketExt` contains a lot of helpful methods/nice interface to deal with the unix control socket. However, this is all tightly coupled with the application's extension system (for example, you can't delay creation of this helper, nor you can have more of them.

We should move all this useful code into a reusable place so the user can create listeners on demand and the `UnixSocketExt` should just parse the config, instantiate the object that just works and act as a proxy for the application.

**Comment by gavin-norman-sociomantic** [comment]
Done in v4.x.x. https://github.com/sociomantic-tsunami/ocean/pull/534
