### ISSUE TITLE
Difference in StringStructSerializer's D1 and D2 output

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/ocean#526]
```D
import ocean.io.Stdout;
import ocean.io.serialize.StringStructSerializer;

struct S (ubyte Version)
{
    const ubyte x = Version;
}

void main()
{
    S!(7u) s;

    scope ser = new StringStructSerializer!(char)();
    char[] output;

    ser.serialize(output, s);
    Stdout.formatln(output).flush;
}
```

D1 build:

```
struct S!(7u):

```

D2 build:

```
struct S!cast(ubyte)7u:
   const(ubyte) x : 7

```

So, not just that some casts are shown, but `const` fields are included in D2 but not in D1's output.

**Comment by nemanja-boric-sociomantic** [comment]
The `cast(ubyte)` difference comes from `S.stringof` expression here: https://github.com/sociomantic-tsunami/ocean/blob/8259558393a69fab5c504f0660a536d66dc5fe2d/src/ocean/io/serialize/StructSerializer.d#L281

```D
struct S (ubyte Version)
{
    const ubyte x = Version;
}

void main()
{
    S!(7u) s;
    pragma(msg, typeof(s).stringof);
}
```

D1:

```
S!(7u)
```

D2:

```
S!cast(ubyte)7u
```

**Comment by nemanja-boric-sociomantic** [comment]
The second difference comes from `tupleof`:

```D
import core.stdc.stdio;

struct S (ubyte Version)
{
    const ubyte x = Version;
}

void main()
{
    S!(7u) s;
    foreach (i, ref field; s.tupleof)
    {
        printf("%.*s\n", typeof(field).stringof.length, typeof(field).stringof.ptr);
    }
}
```

D1:

```
```

(nothing)

D2:

```
const(ubyte)
```

**Comment by stefan-koch-sociomantic** [comment]
This is because D1 does not have const as type-qualifier.
the way forward is to strip consts transitively before taking the stringof of the type.
however is a little unpleasant.

**Comment by nemanja-boric-sociomantic** [comment]
For the first case - there's no const involved. For the second case we need to strip out the entire `const` field, not just `const`, which is also unfortunate (or fortunate, depends what do you think the "truth" is).

**Comment by mihails-strasuns-sociomantic** [comment]
First case is known and we couldn't find any reliable solution other than switching versioned structs to use `int` (fortunately it doesn't affect runtime).

Second problem should not exist because such `const` is converted by `d1to2fix` to `static immutable` and static fields are not part of `.tupleof`.

**Comment by leandro-lucarella-sociomantic** [comment]
I hope this is very harmless if we are closing as **wontfix**.

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic it can be dangerous if someone relies on `stringof` output for something other than user-friendly text representation but sad truth is we can't really do anything reasonable about it. Output of `.stringof` is undefined by spec and may change arbitrarily between releases, we can't even blame upstream here :)
