### ISSUE TITLE
Support TaskExt in CliApp

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/ocean#532]
Currently `CliApp` does not support `TaskExt` as an option, which means that it is not possible to have `CliApp.run` run in a task context, and that the onus is still on the developer to set up task scheduling and eventloops.  It would be nice to support this use-case more straightforwardly.

A small spanner in the works is how to manage the scheduler setup, given that `CliApp` does not read config.

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/533
