### ISSUE TITLE
Enhance expiring cache with per-record lifetime

### ISSUE THREAD

**Issue by ben-palmer-sociomantic** [sociomantic-tsunami/ocean#539]
The current expiring cache implementation has a lifetime value that is set in the constructor (https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/container/cache/ExpiringCache.d#L84) making it impossible to store different records for different lifetimes in the same cache. To do this currently would require multiple caches which complicates application logic.

It would be nice if different lifetimes for records in the same cache were possible so, for example, records expected to change frequently have a short lifetime and more stable records have a longer lifetime.

**Comment by gavin-norman-sociomantic** [comment]
We can investigate this for v3.10.0.

**Comment by mihails-strasuns** [comment]
Started working on this. Looks like easiest solution would be instead to have two separate lifetimes per cache - default one, and one used for missing/erroneous records. This will be much less intrusive change than modifying cache hierarchy to support additional per-record field.

**Comment by gavin-norman-sociomantic** [comment]
>missing/erroneous records

This isn't mentioned in the original issue description. I guess you're just making an example of how this feature might be used?

**Comment by mihails-strasuns** [comment]
Yes, we have quickly discussed this with @ben-palmer-sociomantic and it is actual use case.

**Comment by ben-palmer-sociomantic** [comment]
Just want to be clear, we may want different behavior for missing and erroneous records.

**Comment by mihails-strasuns** [comment]
@ben-palmer-sociomantic how do you distinguish those in cache?

**Comment by ben-palmer-sociomantic** [comment]
But this might be going over the top, initially treating them the same is an improvement.
