### ISSUE TITLE
DaemonApp's usage example shouldn't register SIGTERM

### ISSUE THREAD

**Issue by gkotian** [sociomantic-tsunami/ocean#542]
DaemonApp [always registers SIGTERM](https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/DaemonApp.d#L390-L391) in the list of handled signals, but the usage example [seems to suggest](https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/DaemonApp.d#L843) that the application needs to register it explicitly.

**Comment by nemanja-boric-sociomantic** [comment]
I'm not sure this is the right approach. User's implementation of the `DaemonApp` does specify handled signals and `onSignal` and IMHO, they should match each other. Even if the `SIGTERM` is in the list implicitly, it is not explicitly, if you choose to override `onSignal` without explicitly calling `super.onSignal`.

Other issue would be if you switch the orders of the `signal` and `super`, you're in a problem:

```
super ();
this.optional_settings.signals = [SIGKILL]; // whoops
```

**Comment by mihails-strasuns-sociomantic** [comment]
I think it was a mistake on my side to define https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/util/app/DaemonApp.d#L390-L391 like this.

It should be  `if (settings.signals.length == 0) settings.signals = [ SIGTERM ];` instead.

**Comment by mihails-strasuns-sociomantic** [comment]
So the documentation is really correct here - one is supposed to define all signals manually if non-default handling is needed. And default sigterm handler is here for those apps who don't have any configuration of their own.

**Comment by gkotian** [comment]
Alright then. I'll close this issue under the assumption that you guys will take care of updating DaemonApp's constructor in an upcoming release.

I'd also like to take this opportunity to thank you guys for your work on ocean. I work on several applications that use this stellar library. Good job!
