### ISSUE TITLE
Adapt `QueryParamSet.opApply` to not include `remaining_elements`

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#559]
`opIn_r` doesn't report these extra values as being present, but `opApply` iterates over them. This is a pretty inconsistent API.

See discussion at https://github.com/sociomantic-tsunami/ocean/pull/558/files#r205364031.

**Comment by mihails-strasuns** [comment]
New decision is to deprecate the class completely as its additional functionality is not actually used in our codebase.
