### ISSUE TITLE
ArgumentsExt should throw exception on error

### ISSUE THREAD

**Issue by mihails-strasuns** [sociomantic-tsunami/ocean#569]
@nemanja-boric-sociomantic : 

> `ArgumentsExt` on error prints the error to the formatted output passed to it (by default Stderr). I think it would be better if it would throw some kind of exception which user could catch (or not) and let the runtime to print it out to stderr, or handle in some other way (for example, this makes it very hard to close `stderr` on start of the application and rely on syslog).

**Comment by mihails-strasuns** [comment]
Looking into this I am leaning towards closing this issue as wontfix. `ArgumentsExt` is designed to allow zero-effort default CLI behavior for apps, decoupling interactivity from it makes the extension rather pointless.

For applications relying on syslog it makes more sense to drop `ArgumentsExt` completely and work with arguments manually.

@matthias-wende-sociomantic @gavin-norman-sociomantic opinions?

**Comment by matthias-wende-sociomantic** [comment]
I don't have any opinion on that. I'd say let's close it as probably nobody is going to work on it anyway in the foreseeable future.
