### ISSUE TITLE
Problems with ocean.core.array.Transformation and arrays of references

### ISSUE THREAD

**Issue by mihails-strasuns** [sociomantic-tsunami/ocean#574]
@gavin-norman-sociomantic : 

> For example, passing an array of objects to filter() fails to compile. The reason is that the input array is declared as in T[] (i.e. scope const T[]), as it must not be modified in the function. This array is iterated over, yielding elements of type const T. These are then appended to the output array, of type T[]. Appending a const reference to a non-const array is a compile error.

**Comment by mihails-strasuns** [comment]
It is quite a touch call @gavin-norman-sociomantic - basically, one need to have a `const` buffer for this to work and D type system currently disallows this (`enableStomping` call won't compile) because it may refer to immutable memory.

And if `const` is simply removed, filter will stop working with regular string literals. One solution that could work is to use `inout` and modify `Buffer` to cast away constness when calling `enableStomping` but that is easy path to UB if misused.

What do you think?

**Comment by gavin-norman-sociomantic** [comment]
Ahh I see. That's... rather annoying. Sounds like time for another language feature to me ;)

Another solution would be to make an alternate version of this function that will work with arrays of references. This would presumably not work with immutable arrays of refs, but that's an obscure case. Not a particularly nice solution, but it seems better than opening the door to undefined behaviour.

**Comment by mihails-strasuns** [comment]
Well, in D2-only code we can fix it by defining two overloads - one for reference type `T` and the other for value type `T`. But this requires template constraints, not available in D1.

**Comment by gavin-norman-sociomantic** [comment]
Ah nice. Could an intermediate stage be to define these as separate functions (with different names), then when we drop D1 to move them to overloads? (I'm not sure there's a practical need for this right now. Just musing on possible solutions, should someone desperately need this support.)

**Comment by mihails-strasuns** [comment]
I think so. But I'd probably wait until it is truly needed before committing to such workaround.

Makes me wonder if we can declare ocean v6 or v7 to be D2-only considering current migration progress. Worth checking with Luca once he is back.

**Comment by gavin-norman-sociomantic** [comment]
Agreed on both counts :+1:

**Comment by mihails-strasuns** [comment]
https://github.com/sociomantic-tsunami/ocean/issues/613
