### ISSUE TITLE
Add exclusiveGroup feature to command-line parameter API

### ISSUE THREAD

**Issue by mihails-strasuns** [sociomantic-tsunami/ocean#592]
@andrej-mitrovic-sociomantic : 

Essentially it would allow us to specify a set of parameters where only one of the parameters is allowed to be specified at the command-line. E.g.:

``` D
// Only one parameter in the "input" exclusive group is allowed to be 
// specified at the command-line
args("file").exclusive("input").aliased('F').params(1);
args("server").exclusive("input").aliased('S').params(1);
```

```
# ok
$ ./myapp --file=/foo/bar

# ok
$ ./myapp --server=192.168.1.1

# fail: file and server are exclusive to one another
$ ./myapp --file=/foo/bar --server=192.168.1.1
```

Maybe we should also have group and requiredGroup. group would allow no params, and the required one would require exactly one param.

**Comment by Geod24** [comment]
Sounds like [conflicts](https://github.com/sociomantic-tsunami/ocean/blob/0aeb92d5294e9bf92b95b36f165762946c65e311/src/ocean/text/Arguments.d#L151-L163) ?

**Comment by andrej-mitrovic-sociomantic** [comment]
Thank you @Geod24, very cool!

You seem like a smart guy. Did you know [we're hiring](https://www.sociomantic.com/careers/)?
