### ISSUE TITLE
Convert ocean to be D2-only from one of next majors

### ISSUE THREAD

**Issue by mihails-strasuns** [sociomantic-tsunami/ocean#613]
With current state of application migration is becomes viable to consider cleaned up D2-only version of ocean, either v6 or v7 depending on how soon next major will need to come out. We would need to provide special on demand support of last D1 branch for applications that lag behind but many will be able to switch by the time it is released.

**Comment by mihails-strasuns** [comment]
Considering that pretty much all internal apps are at final transition stage now and current ocean development is very slow, it seems doable to go for D2-only in next major (v5.0.0). Scheduling.

**Comment by gavin-norman-sociomantic** [comment]
Sounds good to me :+1:

**Comment by mihails-strasuns** [comment]
Done via https://github.com/sociomantic-tsunami/ocean/pull/681
