### ISSUE TITLE
Closure-allocation CI script hardcodes assumption of D1 => D2 conversion

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/ocean#648]
The `ci/closures.sh` script used to check for closure allocations makes a hardcoded assumption that the code being checked is D1 and therefore needs to be converted to D2 before the check is made, using `make d2conv`.

However, this does not apply when used with a `+d2` release, or a dependent codebase that is D2-only.  The script should not run `make d2conv` in this case.

(Example use-case is with dmxnet: https://github.com/sociomantic-tsunami/dmxnet/pull/89 where we would like to have the closure allocation check, but can't use this while converting to D2-only.  We can work around simply by just copying the script and deleting the conversion, but it'd be nice to have one simple solution for this.)

**Comment by nemanja-boric-sociomantic** [comment]
I don't think it's the idea that you use `ci/` directory from ocean in your project, though. You should have a copy of the script, or the script should be a part of beaver, because we're that doesn't fall into semver guarantees (we usually change it as a part of minor and sometimes even patch release).

**Comment by joseph-wakeling-sociomantic** [comment]
Hmmm well.  It _is_ being used that way in some projects (e.g. swarm), although I agree it's probably not really the intended use-case.

I do think it's a problem though that it can't be run on `+d2` auto-converted releases.

**Comment by nemanja-boric-sociomantic** [comment]
Nope, swarm has it's own copy:

https://github.com/sociomantic-tsunami/swarm/blob/v5.x.x/.travis.yml#L55
https://github.com/sociomantic-tsunami/swarm/blob/v5.x.x/ci/closures.sh

**Comment by nemanja-boric-sociomantic** [comment]
However, you're right that something is wrong with the` +d2` builds:

https://travis-ci.org/sociomantic-tsunami/ocean/builds/442572615

**Comment by joseph-wakeling-sociomantic** [comment]
> Nope, swarm has it's own copy:

Well, duh.  I'm sure there _is_ at least one project that uses ocean's script directly, though.

**Comment by joseph-wakeling-sociomantic** [comment]
For D2-only projects, though, I'm overthinking it: it should suffice to just do the `make fasttest | grep "closure"` directly (cf. the updated dmxnet PR), assuming that `DFLAGS=-vgc` is set in `env`.

**Comment by mihails-strasuns** [comment]
Should be fixed now for ocean
