### ISSUE TITLE
Re-add reverted throttler consistency check

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/ocean#657]
https://github.com/sociomantic-tsunami/ocean/pull/640 was released but then reverted, as it introduced a breaking change. (Applications that use a throttler in conjunction with a swarm neo suspendable request encountered runtime errors. See https://github.com/sociomantic-tsunami/ocean/pull/651.)

**Comment by mihails-strasuns** [comment]
Currently blocked on swarm fix

**Comment by mihails-strasuns** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/692
