### ISSUE TITLE
Task tests cause assertion failure with debug runtime

### ISSUE THREAD

**Issue by mihails-strasuns** [sociomantic-tsunami/ocean#671]
Normally we use runtime built without assertions (for both D1 and D2) because those are too slow for production. When debugging unrelated issue I have tried running ocean with manually built runtime with all assertions in place and it has triggered this:

```
Unhandled exception in task 0X00007F425A843F00 (ocean.task.util.TaskSuspender_test.Generator)
	Assertion failure (core.thread:2991)
```

This sounds pretty damn bad.

**Comment by Geod24** [comment]
Which commit / tag ?

**Comment by mihails-strasuns** [comment]
v4.x.x head

**Comment by mihails-strasuns** [comment]
FYI: the failed assertion is about trying to reset a fiber that has not terminated yet

**Comment by Geod24** [comment]
> v4.x.x head

I meant of the runtime. Couldn't find any assert in `core.thread` at line 2991 in 2.071 nor 2.078 nor HEAD.

**Comment by mihails-strasuns** [comment]
That was from D1 tangort build :)

**Comment by mihails-strasuns** [comment]
(version 1.10.3 specifically)

**Comment by mihails-strasuns** [comment]
D2 runtime doesn't seem to have same limitation
