### ISSUE TITLE
Auto conversion to D2 for tags is failing

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/ocean#674]
See: https://travis-ci.org/sociomantic-tsunami/ocean/builds/485820133

```
./src/ocean/core/Test.d(230): Error: semicolon expected following function declaration
./src/ocean/core/Test.d(232): Error: declaration expected, not 'if'
./src/ocean/core/Test.d(236): Error: declaration expected, not 'else'
./src/ocean/core/Test.d(241): Error: unrecognized declaration
./src/ocean/io/model/IConduit.d(311): Error: redundant attribute 'scope'
./src/ocean/io/model/IConduit.d(313): Error: redundant attribute 'scope'
./src/ocean/io/model/IConduit.d(330): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(230): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(300): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(368): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(368): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(653): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(799): Error: redundant attribute 'scope'
./src/ocean/text/convert/Formatter.d(857): Error: redundant attribute 'scope'
./src/ocean/core/Buffer.d(116): Error: semicolon expected following function declaration
./src/ocean/core/Buffer.d(118): Error: basic type expected, not return
./src/ocean/core/Buffer.d(118): Error: no identifier for declarator _error_
```

**Comment by leandro-lucarella-sociomantic** [comment]
And FYI @mihails-strasuns even when you don't have time. I wonder if @Geod24 wants to have a look :smiling_imp:

**Comment by Geod24** [comment]
Is it ? I haven't looked into the pipeline in a while but [this](https://travis-ci.org/sociomantic-tsunami/ocean/builds/485808126) is the job for v4.5.0.
The `D2 release` job [at the very bottom](https://travis-ci.org/sociomantic-tsunami/ocean/jobs/485808138) was successful. And indeed [the tag is here](https://github.com/sociomantic-tsunami/ocean/releases/tag/v4.5.0%2Bd2).

But the job you are linking to was triggered on this converted code, and while it seems to be using a D2 compiler, it runs `make d2conv` on it, which is the source of the syntax errors.

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, it is. When a new tag is done, it is automatically converted to D2 and the D2 tag is created. Then Travis triggers a new build for the new D2 tag, and that one is the one failing.

![image](https://user-images.githubusercontent.com/2684688/51990941-ca517900-2488-11e9-84da-db69c22488e3.png)

> But the job you are linking to was triggered on this converted code, and while it seems to be using a D2 compiler, it runs `make d2conv` on it, which is the source of the syntax errors.

OK, now I have to figure out why is triggering the conversion when it didn't before... :grumpy:

**Comment by leandro-lucarella-sociomantic** [comment]
v4.4.4 worked fine, so comparing v4.4.4 and v4.5.0, I see this funny bit:

https://github.com/sociomantic-tsunami/ocean/compare/v4.4.4...v4.5.0#diff-354f30a63fb0907d4ad57269548329e3R42

**Comment by leandro-lucarella-sociomantic** [comment]
It looks like a false positive, as it is only overriding the script that is the same but without output redirection.

**Comment by leandro-lucarella-sociomantic** [comment]
Beaver submodule was advanced, maybe that's it.

**Comment by leandro-lucarella-sociomantic** [comment]
Is the closure checking code:
```
$ ci/closures.sh
+export DFLAGS=-vgc
+DFLAGS=-vgc
+beaver dlang make d2conv
```
https://travis-ci.org/sociomantic-tsunami/ocean/builds/485820133#L756

But this is getting weirder, tests are not being run at all for the D2 tag. Only the closure check is (and it is performing the conversion unconditionally). @mihails-strasuns are test not being run for the D2 tags intentionally?

https://github.com/sociomantic-tsunami/ocean/blob/v4.x.x/.travis.yml#L30

**Comment by leandro-lucarella-sociomantic** [comment]
I have no idea why this worked in v4.4.4 (and previously), as the conversion was also performed. Maybe is because of , and before it failed by the script exited with status 0 anyway, because nothing was tested afterwards.

Anyway, this should fix it: https://github.com/sociomantic-tsunami/beaver/pull/66

**Comment by leandro-lucarella-sociomantic** [comment]
After the submodule is advanced, I don't see any reason not to enable tests in the D2 tag (we need to make all D1 tests only run for non-tags though).

**Comment by Geod24** [comment]
> But this is getting weirder, tests are not being run at all for the D2 tag.

To me that makes sense: tests are run before the tag is pushed (you don't want to push a tag which is broken). Re-testing after push does sounds that useful (unless you want to be paranoid).

**Comment by leandro-lucarella-sociomantic** [comment]
I want to be paranoid. It happened before that we had something wrong with the tag and went unnoticed.
