### ISSUE TITLE
`ocean.sys.Stats.d` reports infinite memory percentage usage.

### ISSUE THREAD

**Issue by scott-gibson-sociomantic** [sociomantic-tsunami/ocean#69]
Example logfile - `2017-04-07 13:32:22,893 cpu_user:89.94 cpu_system:9.89 cpu_total:99.83 vsz:224120832 rss:190791680 mem_percentage:inf`

Server reports 62.7G RAM.

**Comment by nemanja-boric-sociomantic** [comment]
Fixed in #70
