### ISSUE TITLE
`Unqual` template does not strip topmost qualifier for pointers

### ISSUE THREAD

**Issue by tiyash-basu-sociomantic** [sociomantic-tsunami/ocean#704]
Apparently, the `Unqual` template does not un-qualify qualified pointer types, as indicated in the following tests. The `Unqual` template could be extended to support pointer types as well.

These tests pass:
```D
import ocean.meta.types.Qualifiers;

// Passes
unittest
{
    static assert(is(Unqual!(const int) == int));
}

// Passes
unittest
{
    static assert(is(Unqual!(Const!(int)) == int));
}
```

However, these fail:
```D
import ocean.meta.types.Qualifiers;

// Error: static assert  is(const(int)* == int*) is false
unittest
{
    static assert(is(Unqual!(const (int*)) == int*));
}

// Error: static assert  is(const(int)* == int*)
unittest
{
    static assert(is(Unqual!(Const!(int*)) == int*));
}
```

**Comment by gavin-norman-sociomantic** [comment]
Ah interesting, so it's not just `void*`.

**Comment by Geod24** [comment]
That's consistent with what Phobos is doing though. Unqual only removes the topmost layer, so `Unqual!(const(int*)) == const(int)*`.
But most people expect Unqual to go all the way in my experience.

**Comment by Geod24** [comment]
Closing as WONTFIX since it's a well known behavior.
