### ISSUE TITLE
Deprecation message refers to non-existent `isStringType`

### ISSUE THREAD

**Issue by don-clugston-sociomantic** [sociomantic-tsunami/ocean#722]
In ocean.core.Traits there is a declaration
```
deprecated("Use ocean.meta.traits.Basic.isStringType")
template isStringType( T )
```

But, `ocean.meta.traits.Basic.isStringType` does not exist. That's really mean!

**Comment by matthias-wende-sociomantic** [comment]
Updated in https://github.com/sociomantic-tsunami/ocean/pull/713 but not released yet.
