### ISSUE TITLE
Branch v5.x.x should be made the default

### ISSUE THREAD

**Issue by Geod24** [sociomantic-tsunami/ocean#770]
According to the README, branch v4.x.x is out of support, hence it should be deleted, along with other `v4` patch branches, and `v5.x.x` should be made the default branch.
There probably needs to be a review of the milestones assignment.

**Comment by ben-palmer-sociomantic** [comment]
Thansk for the reminder. I have been through the milestones and have hopefully got everything required sorted. I will close this issue but feel free to comment or re-open if I missed something.
