### ISSUE TITLE
BitArray.init name is problematic

### ISSUE THREAD

**Issue by AndrejMitrovic** [sociomantic-tsunami/ocean#781]
https://github.com/sociomantic-tsunami/ocean/blob/ad2c368b338d74cdd6991e5c32b1c042250ebef0/src/ocean/core/BitArray.d#L206

This is causing issues with generic code. For example, `BitArray.init` cannot be used because it's "overriden" here, leading to a compiler error.

I suggest renaming it to `initialize`. But I don't know if this is used anywhere within Sociomantic, so it's up to you guys to decide if it's worth renaming or if it has to go through a deprecation phase first. I think it's probably not used anywhere because there are no annotations in this struct.

**Comment by don-clugston-sociomantic** [comment]
This appears to be fixed by #784.
