### ISSUE TITLE
code.dlang.org repository URL is outdated

### ISSUE THREAD

**Issue by s-ludwig** [sociomantic-tsunami/ocean#788]
Just stumbled over the fact that the ocean-d2 package on code.dlang.org still references "sociomantic-tsunami/ocean-d2" instead of "sociomantic-tsunami/ocean" and didn't get any updates since 2017. This can be changed under "Manage packages" -> "ocean-d2" -> "Repository".

**Comment by Geod24** [comment]
CC @mihails-strasuns @llucax

**Comment by llucax** [comment]
I think ocean never really had an "official" dub package, it was done as an experiment in this other repo. Since I'm not involved in Ocean anymore, pinging @ben-palmer-sociomantic @daniel-zullo-sociomantic and @joseph-wakeling-frequenz as people that might be interested in getting proper dub support in ocean.

**Comment by mihails-strasuns** [comment]
AFAIR Hatem has originally created that dub package so there is a high chance account access is lost now. Better probably to remove it and re-create anew if needed.

**Comment by s-ludwig** [comment]
I could also change the owner manually to anyone else who has an account there.

**Comment by mihails-strasuns** [comment]
That is a call for current ocean maintainers to make :)

**Comment by ben-palmer-sociomantic** [comment]
I think we should remove it as it is outdated and we are not planning on maintaining a dub package. If anyone else wants to take it on though they can feel free.

**Comment by don-clugston-sociomantic** [comment]
Hatem created this package from personal interest, in relation to a presentation he gave at dconf. We don't use dub internally so it's unsurprising that it's hopelessly outdated.

**Comment by mihails-strasuns** [comment]
Note that there is a `dub.sdl` in the default ocean branch but it is not tested by the ocean CI. If it was, updates to the registry would come for free (afair code.dlang.org checks new versions of registered repos automatically).

Maybe that is something @joseph-wakeling-frequenz wants to take over? I have memories that you have used ocean via dub.

**Comment by joseph-wakeling-frequenz** [comment]
I haven't really used it so far, I just made a few provisional tests of using dub rather than make to build/test the library.  I'll think about what I can do but in the short term I would be reluctant to take on something I'm not 100% sure I can commit to.

**Comment by Geod24** [comment]
I see two points here:
- The registry registration;
- The `dub.sdl` file in Ocean's default branch;

The `dub.sdl` file works just fine, and we are using it. I surely hope it won't go away.
The registry registration is the part that is broken. We (obviously) don't use it, relying on submodules instead, but since it is a rather low maintenance thing, you can assign it to me @s-ludwig .

**Comment by ben-palmer-sociomantic** [comment]
Thanks @Geod24 !

**Comment by s-ludwig** [comment]
@Geod24: Done!

**Comment by Geod24** [comment]
@s-ludwig : Actually it seems that the name of the package and the Github repository need to match ??

> The package name of the new repository doesn't match the existing one: ocean

So I just deleted it (there were 17 total downloads anyway) and re-created it, proper: http://code.dlang.org/packages/ocean

**Comment by oraby** [comment]
Just to bring context to the reasoning behind the decision back then: I've created the dub entry under the name  `ocean-d2` such that I'd leave the entry named just `ocean` to when the actual ocean repo (one this repo) is  in D2.
The goal back then was to have the ocean-d2 repo automatically converted with each ocean release. This plan was dropped quickly afterwards though in favour of other plans. I wasn't part though of that decision process.

If I remember correctly, the reasoning behind using a personal account was actually to avoid the situation where we need to update the repo info but we lose the access to the sociomantic email. All of that happened, but you've guys managed already in other ways :+1: .

**Comment by Geod24** [comment]
@Oraby: Thanks for the context :)

I think this issue can be closed
