### ISSUE TITLE
Drop dependency on DMD < v2.075

### ISSUE THREAD

**Issue by Geod24** [sociomantic-tsunami/ocean#804]
Because of the upcoming `body` deprecation (in favor of `do`), building any Sociomantic project with DMD >= 2.091.0 is going to result in a torrent of message.
I could solve those messages myself very easily, however the `do` alternative was introduced in DMD v2.075.0, and it seems Ocean & co are still tested with DMD 2.071 (socio edition).

Given the recent developments, is there a chance that the minimum compiler be upgraded in the near future ?

CC @don-clugston-sociomantic

**Comment by don-clugston-sociomantic** [comment]
Good Lord, dlang is doing their level best to make this language unusable. If you're making breaking changes like this, there *must* be a stability branch before them. Sadly, the most recent stability branch is called D1.

The short answer is, no, not in the short term. We need to support 2.071 socio at least until August this year. After that point we could bump the minimum supported version to 2.090.
Currently, the *only* usable versions are 2.090 and 2.071 socio. They are the only compiler releases which make binaries which work on Ubuntu 18.04 (Bionic) and later. Everything else is broken.

My focus is to make our repos compile cleanly on 2.090.1. There's no interest at present in anything beyond that.

**Comment by Geod24** [comment]
To be fair, I am the one that pushed for this deprecation.

I agree that the release schedule should be better handled, but so far it's only a volunteer effort, so it's a tradeoff between moving forward and being stable. It seems the vast majority (at least the non-silent one) prefers moving forward.

If it's a bother for Sociomantic, I suggest bringing it up to Walter so we get the deprecation reverted before the release. I'm good with either, just trying to plan ahead what the best possible way is for everyone.

Note that we do use some (minor) parts of Ocean, so I have a vested interest in not being flooded with deprecation messages.

**Comment by don-clugston-sociomantic** [comment]
Once dmd 2.092 is released I think we'll be able to drop support for old versions. Reason is, compilers older than 2.091 have wrong-code bugs which means they shouldn't be used. We have some existing projects which require our custom compiler, which is 2.075 with patches applied, but they are using old releases of ocean. Nothing will be changing to a recent version of ocean without changing the compiler.

**Comment by Geod24** [comment]
What fixes do you need which will be in 92 but aren't in 91?

**Comment by Geod24** [comment]
Also, if you go to something >= 2.089 we can remove more `stdc` module.
See e.g. https://github.com/dlang/druntime/commit/a2a88cf05cccbf70e7a1df167d28a45b827da5d4

**Comment by Geod24** [comment]
Done in #829
