### ISSUE TITLE
SmartUnion generates conflicting opCalls

### ISSUE THREAD

**Issue by MoonlightSentinel** [sociomantic-tsunami/ocean#827]
`SmartUnion` generates an `opCall` for every member of a given `union`, even if the union contains multiple members with identical types. This bug is silently accepted because of [this issue](https://issues.dlang.org/show_bug.cgi?id=2789) and blocks dlang/dmd#8429 which enables a deprecation for conflicting overloads.

**Comment by Geod24** [comment]
PR #831 merged.
