### ISSUE TITLE
New release needed to unblock dmd's buildkite

### ISSUE THREAD

**Issue by dkorpel** [sociomantic-tsunami/ocean#857]
This PR: https://github.com/sociomantic-tsunami/ocean/pull/852
Is needed to make buildkite pass for this dmd PR: https://github.com/dlang/dmd/pull/12890
But buildkite checks out tag 6.1.0 from April, which doesn't include the fix.

I've tried contacting Matthias Lang with a GitHub ping and a Slack message, but he seems to be busy, so hopefully this issue is seen by someone who can make it happen.

**Comment by Geod24** [comment]
Thanks, this slipped my mind. New release out: https://github.com/sociomantic-tsunami/ocean/releases/tag/v6.2.0
Looking at Buildkite though, it looks like swarm & co also need to be updated.

**Comment by dkorpel** [comment]
> looks like swarm & co also need to be updated

Can you do that please?
