### ISSUE TITLE
Replace `pragma` with `static assert` in serializer and re-enable relevant tests

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/ocean#95]
Follow-up for https://github.com/sociomantic-tsunami/ocean/pull/94 to be done in next major release. Informational warning about using `const` with deserializer should be replaced with hard assertion and tests that ensure such code is rejected has to be re-enabled.

**Comment by don-clugston-sociomantic** [comment]
Note that `dive.net.curl.CurlProcessSingle` uses the deserializer on `const` fields. Many of these fields are string literals.

**Comment by gavin-norman-sociomantic** [comment]
This is the struct which is deserialized: https://github.com/sociomantic/dive/blob/v3.x.x/src/dive/net/curl/process/RequestParams.d#L88

**Comment by mihails-strasuns-sociomantic** [comment]
This is going to be a big problem - while modifying request params processing either to not require const or not use serializer is not that hard, most of affected fields/functions are public and the module is used in many different projects.

Investigating various options currently.

**Comment by mihails-strasuns-sociomantic** [comment]
Looking at the dive code again I wonder why serializer trick is used there at all, considering API relies on builder pattern anyway. Why can't it copy arguments when setting them? i.e. turn https://github.com/sociomantic/dive/blob/v3.x.x/src/dive/net/curl/process/RequestSetup.d#L597 into `req.params.copy(url)` and so on?

**Comment by mihails-strasuns-sociomantic** [comment]
Ah, right, I remember now - because request struct is not reused on user side and that would allocate each time.

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/152
