### ISSUE TITLE
Ocean must pass tests when run with `-release`

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/ocean#96]
Essentially another form of the goal to clean up `assert` usage in ocean to make `-release` flag feasible for our applications. Right now it doesn't even pass tests because some failed assertions are checked with `testThrown`.

**Comment by mihails-strasuns-sociomantic** [comment]
For the reference, the one failure I noticed was `./src/ocean/core/SmartUnion.d:139: test error: Expected 'Exception' to be thrown, but it wasn't`

**Comment by nemanja-boric-sociomantic** [comment]
For the reference, I think the problem with the `SmartUnion` isn't the assert vs enforce, but `in` contract: https://github.com/sociomantic-tsunami/ocean/blob/v3.x.x/src/ocean/core/SmartUnion.d#L506

**Comment by mihails-strasuns-sociomantic** [comment]
contract == assert
