### ISSUE TITLE
Imported symbols cannot be exposed through aggregate

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/ocean#99]
Thanks to the new import rules in 2.071.0+, the design of `LibFeatures` doesn't work.

The definition is currently:
```D
module ocean.LibFeatures;

static immutable has_features_2_7 = true;
static immutable has_features_2_6 = true;
static immutable has_features_2_5 = true;
static immutable has_features_2_4 = true;
static immutable has_features_2_3 = true;
static immutable has_features_2_1 = true;
static immutable has_features_2_0 = true;
```

And the usage is:
```D
private bool hasFeaturesFromFunc ( istring libname, ulong major, ulong minor ) ()
{
    struct Library
    {
        mixin("import " ~ libname ~ ".LibFeatures;");
    }

   // Generates `return is(typeof(Library.has_features_2_0));` for example
    mixin("return is(typeof(Library.has_features_"
        ~ ctfe_i2a(major) ~ "_" ~ ctfe_i2a(minor) ~ "));");
}
```

However this doesn't work with new import rules, which make import scope not accessible from outside of an aggregate.
CC @mihails-strasuns-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
Damn, I rely on this behaviour in quite some places. Do you know if `public import` works in such context?

**Comment by mathias-lang-sociomantic** [comment]
> Do you know if `public import` works in such context?

It does not. `import` within an aggregate's scope is completely inaccessible from outside this aggregate nowadays (including deriving classes).

**Comment by mihails-strasuns-sociomantic** [comment]
http://forum.dlang.org/post/pmezncogehwjnvjrxwns@forum.dlang.org
http://forum.dlang.org/post/mr33a2$26ut$1@digitalmars.com

I probably should file a regression report to bugzilla >_<

**Comment by mathias-lang-sociomantic** [comment]
We had some discussions in:
- https://issues.dlang.org/show_bug.cgi?id=15966
- https://issues.dlang.org/show_bug.cgi?id=15925

I don't know how doable it'll be to convince Walter. ATM I cannot think of a failure scenario, but that'll make some code odd (because you'll allow `public import` but they wouldn't be 'inherited').

**Comment by gavin-norman-sociomantic** [comment]
>It does not. import within an aggregate's scope is completely inaccessible from outside this aggregate nowadays (including deriving classes).

Does this include within the same module? e.g.
```D
struct Something
{
  import something.else : aFunction;
}

Something.aFunction(); // is this ok?
```

**Comment by mathias-lang-sociomantic** [comment]
Yes and no.
If you look at the `import` of `hasFeatureFromFunc`, it is in the same module, which covers your question (TL;DR: Doesn't work).

However your example would work, but only because selective imports are a special case: they introduce an alias in the scope they are in.

**Comment by mihails-strasuns-sociomantic** [comment]
https://issues.dlang.org/show_bug.cgi?id=17433
Will poke Martin/Walter via mail too.

**Comment by mihails-strasuns-sociomantic** [comment]
Using specialized imports can be used as a workaround in some cases but I would like a more principled direction.

**Comment by mathias-lang-sociomantic** [comment]
> Using specialized imports can be used as a workaround in some cases but I would like a more principled direction.

Specialized imports are awful because they're inconsistent with the `import` semantic.
```D
public void format (Args...) (Args args) { assert(0); }

public class Foo
{
    import std.format : format;

    void foo ()
    {
        format("%s", "Hello world");
    }
}

void main ()
{
    scope f = new Foo;
    f.foo;
}
```

This won't trigger the `assert`.

```D
public void format (Args...) (Args args) { assert(0); }

public class Foo
{
    import std.format;

    void foo ()
    {
        format("%s", "Hello world");
    }
}

void main ()
{
    scope f = new Foo;
    f.foo;
}
```

But this will, because it magically introduces an `alias`. I consider this a bug.

**Comment by mihails-strasuns-sociomantic** [comment]
(you probably mean other way around, specialized ones introduce an alias)
Yeah, I agree that this either bug or misdesign though don't have high hopes it will be fixed. For now I am simply trying to figure out if Walter/Martin are aware of the situation.

**Comment by nemanja-boric-sociomantic** [comment]
Is this fixed in v4.x.x given that we compile with newish compilers these days?

**Comment by mihails-strasuns-sociomantic** [comment]
Yep, I avoided the issue by versioning in plain nested imports for D2 builds.
